name: Deployment Workflow

on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Trigger Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Call Deploy Hook
        run: curl -X POST "${{ secrets.DEPLOYMENT_HOOK }}"
